# ========================
# HandleLocations Settings
# ========================
lang:
  locations-title: ' &e---- &cPublic Locations &e----'
  player-locations-title: ' &e---- &cPrivate Locations ({0}) &e----'
  locations-item: '&f{0} &7({1}: {2}, {3}, {4})'
  no-locations-set: '&fNo locations set.'
  no-locations-to-show: '&fNo locations to show.'
  location-set: '&6Location &c{0} &6set to current location.'
  player-location-set: '&6Location &c{0} &6set for &c{1}&6.'
  location-set-usage: '&f/{0} {1} [<player>:]<location>'
  location-unset: '&6Location &c{0} &6unset.'
  player-location-unset: '&6Location &c{0} &6unset for &c{1}&6.'
  location-unset-usage: '&f/{0} {1} [<player>:]<location>'
  teleporting-to-location: '&6Teleporting to location &c{0}&6...'
  teleporting-to-player-location: '&6Teleporting to &c{0}&6''s location &c{1}&6...'
  teleporting-other-to-location: '&6Teleporting &c{0} &6to location &c{1}&6...'
  teleporting-other-to-player-location: '&6Teleporting &c{0} &6to &c{1}&6''s location &c{2}&6...'
  location-teleport-usage: '&f/{0} {1} [<player>] [<player>:]<location>'
  location-not-found: '&cError: &4Location &c{0} &4not found.'
  player-location-not-found: '&cError: &4Location &c{0} &4not found for &c{1}&4.'
